CEO="Anuwas from Default Profile"

# use %local for local development and %prod for production
%local.quarkus.http.port=8081
%local.CEO="Anuwas  (Local Profile)"

# This value will be displayed even if run from uat profile
COMMONCEO="Anuwas  (Common Profile)"

%prod.CEO="Anuwas  (Production)"

# Here is the command to run the application with local profile
# ./mvnw quarkus:dev -Dquarkus.profile=local -> suggeste from copilot

# another command to run the application with local/production profile
# ./mvnw -Dquarkus.profile=prod compile quarkus:dev -suggested from youtube video
